## This playbook is going to capture remote nodes uptime and disk usage.

## Here are the remote nodes,
[dev] ==> host groupnames
10.0.0.10
10.0.0.11


############################## Playbook starts here ############################

- name: play1
  hosts: all
  tasks:
    - name: checking the uptime of the remote nodes
      shell: uptime
      register: OUT

    - name: Printing the uptime output
      debug:
         msg: "{{ OUT.stdout_lines }}"

    - name: checking the file system of the remote nodes
      shell: df -T
      register: OUT

    - name: print the df output
      debug:
         msg: "{{ OUT.stdout_lines }}"

    - name: Just putting some heading of this overall playbook
      debug: 
         msg: Hello World! Welcome to my learning on Ansible


# Note: when we use "{{ OUT.stdout_lines }} " the df output looks pretty

Note: Here we're using shell,debug are the ansible modules
