## This playbook is going to show us the exit status of any command was successfull without any errors.

## exit status means the command was successful without any errors

####################Playbook starts here ######################################

- name: Demo on exit status
  hosts: all
  gather_facts: True
  tasks:
    - name: Execute Uptime
      shell: uptime
      register: OUT
    - name: Declare Variables
      set_fact:
         STATUS: "{{ OUT.rc }}"

    - name: print exist status
      debug:
         msg: Exit status is {{ STATUS }}

## set_fact is the module to check out the exit status in linux OS
